### ISSUE TITLE
jfairy doesn't work with GlassFish 4.1

### ISSUE THREAD

**Issue by instantiationexception** [Codearte/jfairy#33]
I have no _beans.xml_ file in my Java EE 7 application (implicit bean archive). Deploy fails with error:

    org.glassfish.deployment.common.DeploymentException: CDI deployment failure:Exception List with 2 exceptions:
    Exception 0 :
    org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type BaseProducer with qualifiers @Default
      at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedConstructor] @Inject public org.jfairy.producer.DateProducer(BaseProducer, TimeProvider)
      at org.jfairy.producer.DateProducer.<init>(DateProducer.java:0)
    ...
    Exception 0 :
    org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type BaseProducer with qualifiers @Default
      at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedConstructor] @Inject org.jfairy.data.DataMaster(BaseProducer)
      at org.jfairy.data.DataMaster.<init>(DataMaster.java:0)
    ...

jfairy uses Guice but container (GlassFish 4.1) thinks it uses CDI.
Guava team had a similar problem https://code.google.com/p/guava-libraries/issues/detail?id=1433.

I created _beans.xml_ but it didn't help:

    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
           bean-discovery-mode="annotated">    

        <scan>
            <exclude name="org.jfairy.**"/>
        </scan>
    </beans>

**Comment by jkubrynski** [comment]
@instantiationexception It looks more like a GlassFish issue - not JFairy. I don't know what exactly we could do about it

**Comment by mariuszs** [comment]
`beans.xml` should work, change jfairy package to: `io.codearte.jfairy`

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
       bean-discovery-mode="annotated">    

    <scan>
        <exclude name="io.codearte.jfairy.**"/>
    </scan>
</beans>

**Comment by mariuszs** [comment]
OK, after more reading - this is JEE/CDI issue and was fixed in CDI 1.2.Final

https://issues.jboss.org/browse/CDI-377

**Comment by szpak** [comment]
Closing the issue as it should be fixed with CDI 1.2.Final. Feel free to reopen it if the problem persists.
