### ISSUE TITLE
asm pkg dep conflict with common android build

### ISSUE THREAD

**Issue by lklots** [Codearte/jfairy#44]
When running jfairy on android with roboelectric 3.0+, there is a package dependency mismatch against the asm library. jfairy runs on asm:asm:3.1 which is nearly a decade old while roboelectric run against asm 5.+. The pkg dep output for jfairy is below. 

Injection is good and all but by including it in this library it increases the surface area for conflicts like above. When making the trade-off in terms of library maintainability vs. compatibility I would side on the compatibility especially as in the case of a library like this that really doesn't require injection or joda time etc.  

+--- io.codearte.jfairy:jfairy:0.4.1
|    +--- com.google.guava:guava:[15.0,) -> 19.0-rc1
|    +--- com.google.inject:guice:3.0
|    |    +--- javax.inject:javax.inject:1
|    |    +--- aopalliance:aopalliance:1.0
|    |    \--- org.sonatype.sisu.inject:cglib:2.2.1-v20090111
|    |         \--- asm:asm:3.1 <----------------------------------------- conflict
|    +--- org.yaml:snakeyaml:[1.9,2.0) -> 1.15
|    +--- org.iban4j:iban4j:2.1.1
|    +--- com.google.inject.extensions:guice-assistedinject:3.0
|    |    \--- com.google.inject:guice:3.0 (*)
|    +--- joda-time:joda-time:2.3
|    +--- org.reflections:reflections:0.9.9
|    |    +--- com.google.guava:guava:15.0 -> 19.0-rc1
|    |    +--- org.javassist:javassist:3.18.2-GA -> 3.19.0-GA
|    |    \--- com.google.code.findbugs:annotations:2.0.1
|    +--- org.apache.commons:commons-lang3:3.3.2
|    \--- org.slf4j:slf4j-api:1.7.7

**Comment by jkubrynski** [comment]
@lklots have you tried exluding asm from guice dependency?

**Comment by OlgaMaciaszek** [comment]
@lklots We have raised Guice version to 4.0 in JFairy 0.5.0. This should help.
