### ISSUE TITLE
Getting Started with JFairy

### ISSUE THREAD

**Issue by Schlonger** [Codearte/jfairy#45]
Hey,

New to this API, can anybody point me to documentation that covers setting a dev environment with dependencies?  Looks like there are many!  Anyway - help much appreciated!  

.Chris

**Comment by jkubrynski** [comment]
Hi @Schlonger,

could you explain a little bit what you need? All dependencies are traversed from jfairy.

**Comment by Schlonger** [comment]
Thanks for responding -   Just exploring jfairy to add the demographic data to some other simulated data representing customer buying habits, fraud indicators and credit risk scores - really just writing tables to JDBC.

Just looking for basics - what versions of Java are supported?  What is the recommended build config?  The jfairy project has been around for years, is it stable?   Maybe I'm too new to github/gradle/maven etc.  

I'm literally an old school Java programmer, wrote my engineering thesis on the Java language when it was still a Canadian project named "Oak".  I haven't programmed seriously in years but have a side project to create simulated data to showcase analytical engines.

**Comment by OlgaMaciaszek** [comment]
Hello @Schlonger,

we do our best to avoid introducing any changes that would break backward compatibility, so I guess **jfairy** is stable.

As with any third-party library, there are various way to include it into your code. The most straightforward one is just downloading the jar and including it in your project files, but this would definitely a bad idea for so many reason -the first one of them being the need to add all the dependencies of that jar along-.

[Maven] (https://maven.apache.org) and [Gradle] (https://gradle.org/documentation/) are good tools for managing dependencies and the build process. It will probably take you some time to go through the docs and do your first setup, but it's worth the time invested - you will save a lot of it in the longer run.

Once you have created your pom.xml or build.gradle file, you can find [jfairy in the Maven Repository](http://mvnrepository.com/artifact/io.codearte.jfairy/jfairy) and get the correct reference from there for Maven:
```xml
<dependency>
	<groupId>io.codearte.jfairy</groupId>
	<artifactId>jfairy</artifactId>
	<version>0.4.3</version>
</dependency>
```
or Gradle:
```groovy
'io.codearte.jfairy:jfairy:0.4.3'
```
then the build tool will take care of getting all the necessary jars for you.
As an example, you can check out the `build.gradle` file in the jfairy project and its `dependencies` section.

**Comment by Schlonger** [comment]
Thank you for this, I got the API working fine with Eclipse and the Maven
plug-in.

.Chris


On Wed, Aug 5, 2015 at 10:10 AM, Olga Maciaszek-Sharma <
notifications@github.com> wrote:

> Hello @Schlonger <https://github.com/Schlonger>,
>
> we do our best to avoid introducing any changes that would break backward
> compatibility, so I guess *jfairy* is stable.
>
> As with any third-party library, there are various way to include it into
> your code. The most straightforward one is just downloading the jar and
> including it in your project files, but this would definitely a bad idea
> for so many reason -the first one of them being the need to add all the
> dependencies of that jar along-.
>
> Maven <https://maven.apache.org> and Gradle
> <https://gradle.org/documentation/> are good tools for managing
> dependencies and the build process. It will probably take you some time to
> go through the docs and do your first setup, but it's worth the time
> invested - you will save a lot of it in the longer run.
>
> Once you have created your pom.xml or build.gradle file, you can find jfairy
> in the Maven Repository
> <http://mvnrepository.com/artifact/io.codearte.jfairy/jfairy> and get the
> correct reference from there for Maven:
>
> <dependency>
>     <groupId>io.codearte.jfairy</groupId>
>     <artifactId>jfairy</artifactId>
>     <version>0.4.3</version>
> </dependency>
>
> or Gradle:
>
> 'io.codearte.jfairy:jfairy:0.4.3'
>
> then the build tool will take care of getting all the necessary jars for
> you.
> As an example, you can check out the build.gradle file in the jfairy
> project and its dependencies section.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codearte/jfairy/issues/45#issuecomment-128010351>.
>



-- 
.Chris

**Comment by OlgaMaciaszek** [comment]
You're welcome :)
