### ISSUE TITLE
Please provide an example of PersonProperties.telephoneFormat

### ISSUE THREAD

**Issue by nkelsa1** [Codearte/jfairy#51]
Please can you provide an example of how to use the PersonProperties.telephoneFormat? I am looking for an 11 digit number starting with 0.

Thanks

**Comment by mariuszs** [comment]
Try with something like this:

```
import io.codearte.jfairy.Fairy
import io.codearte.jfairy.producer.person.PersonProperties

def fairy = Fairy.create(Locale.forLanguageTag("en"))
def person = fairy.person(PersonProperties.telephoneFormat('"0###########"'))
println person.fullName() + " : " + person.telephoneNumber()
```

Result:

    Olivia Ford : "025527042802"

**Comment by nkelsa1** [comment]
Thanks Mariusz,

I'll give it a try.

Does jfairy support all locale language or just a subset?

Thanks

**Comment by mariuszs** [comment]
We have suppoort for subset, please take look at:

https://github.com/Codearte/jfairy/tree/master/src/main/resources
