### ISSUE TITLE
Generated emails for company are wrong : mail@mercedes/boschggmbh.com

### ISSUE THREAD

**Issue by sebastienvermeille** [Codearte/jfairy#69]

**Comment by andidev** [comment]
I have also spotted spaces in emails which is not correct

**Comment by andidev** [comment]
Looks like some german company names jfairy_de.yml contains slashes which is causing this issue.

**Comment by sebastienvermeille** [comment]
@andidev yes exactly : mercedes/Bosch (I thought jfairy worked with wikipedia to generate data. Don't ask me why :) )

**Comment by OlgaMaciaszek** [comment]
@andidev , @sebastienvermeille , thanks for your inputs. Sorry for long wait times on this. I will definitely fix it and also review other PRs this week.

**Comment by OlgaMaciaszek** [comment]
The issue has been fixed by @andidev .
