### ISSUE TITLE
Google Guava Dependency causes Version Mismatch Error with Java 7

### ISSUE THREAD

**Issue by ckasek** [Codearte/jfairy#75]
The build.gradle file specifies that any version greater than 15 of Google Guava should be used.

Google has just released Guava 21.0.rc1, which requires Java 8.  Due to this, projects using JFairy that are being compiled with Java 1.7 fail with a Java Version Mismatch, for instance:

`java.lang.UnsupportedClassVersionError: com/google/common/collect/Sets : Unsupported major.minor version 52.0`

**Comment by mariuszs** [comment]
Additionally Guava 20 is required for jfairy.

**Comment by OlgaMaciaszek** [comment]
Released version with fix: https://github.com/Codearte/jfairy/releases/tag/release-0.5.6 . Closing bug.
