### ISSUE TITLE
Cannot get an instance of Fairy since 0.5.5

### ISSUE THREAD

**Issue by ccjmne** [Codearte/jfairy#82]
## The issue

I am trying to load a `static` instance of `Fairy` via `Fairy#create`. My application is left hanging because that instance is never ready.

I get the following exception:

```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
  at io.codearte.jfairy.producer.text.TextProducerInternal.<init>(TextProducerInternal.java:49)
  while locating io.codearte.jfairy.producer.text.TextProducerInternal
    for parameter 0 at io.codearte.jfairy.producer.text.TextProducer.<init>(TextProducer.java:34)
  while locating io.codearte.jfairy.producer.text.TextProducer
    for parameter 0 at io.codearte.jfairy.Fairy.<init>(Fairy.java:37)
  while locating io.codearte.jfairy.Fairy annotated with @com.google.inject.internal.UniqueAnnotations$Internal(value=1)
```

It is worth noting that this exception is actually being swallowed somewhere down the line.

## How to reproduce

Simply run the following piece of code:
```java
public static final Fairy FAIRY = Fairy.create();
```

## Versions affected

- [ ] 0.5.3
- [ ] 0.5.4 - not tested, unavailable on [Maven Repository](http://mvnrepository.com/artifact/io.codearte.jfairy/jfairy)
- [x] 0.5.5
- [x] 0.5.6

Sorry for lacking specifics and not coming up with a PR for this -- I am really busy right now. Just trying to put it out there and let you know. Maybe I'm just missing something huge or you guys just can't reproduce it.

Either way, I'll be sticking to 0.5.3 for now! I might come back to it this weekend.

**Comment by orzeh** [comment]
@ccjmne you probably have different Guava version on _classpath_ and it conflicts.

**Comment by ccjmne** [comment]
Yeah, makes perfect sense; it does seem like some injection issue. I'll
sort out our dependencies as soon as possible.
I am closing this. Thanks!
